name: Deploy to GitHub Pages

on:
  push:
    branches:
      - nextjsfromstart

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout

      - name: Install dependencies
        run: npm install || yarn install

      - name: Build
        run: npm run build || yarn build

      - name: Archive artifact
        uses: actions/upload-pages-artifact
        with:
          name: built-files
          path: pages/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages
        with:
          token: ${{ github.token }}

env:
  GITHUB_PAGES: true
