name: Deploy to GitHub Pages

on:
  push:
    branches: [nextjsfromstart]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install || yarn install

      - name: Build
        run: npm run build || yarn build

     - name: Archive artifact
  run: |
    cp ./out/index.html artifact.html
  with:
    path: artifact.html


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          stale: true # Removes old deployment on branch

env:
  GITHUB_PAGES: true
