name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"] # Trigger on push to main branch
  workflow_dispatch: # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npx next build

      # Note: Do NOT run 'next export' command anymore when using output: 'export'

      - name: Upload static files artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Next.js will output static files here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

      - name: Output page URL
        run: echo "Page available at ${{ steps.deployment.outputs.page_url }}"
